# Generated by Django 2.2 on 2022-11-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='account')),
                ('password', models.CharField(max_length=16, verbose_name='password')),
                ('act_name', models.CharField(max_length=20, null=True, verbose_name='actual name of user')),
                ('email', models.CharField(max_length=30, null=True, verbose_name='email of user')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='mobile of user')),
                ('authority', models.IntegerField(verbose_name='user authority')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
