# Generated by Django 2.2 on 2022-11-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, verbose_name='course name')),
                ('instructor', models.CharField(max_length=60, verbose_name='course instructor')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='ProblemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=40, verbose_name='problem name')),
                ('problem_content', models.TextField(verbose_name='problem content')),
                ('solution_count', models.IntegerField(default=0, verbose_name='solution count')),
            ],
            options={
                'db_table': 'Problem',
            },
        ),
        migrations.CreateModel(
            name='SolutionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=20, verbose_name='solution name')),
                ('solution_content', models.TextField(verbose_name='solution content')),
                ('like', models.IntegerField(default=0, verbose_name='like count')),
            ],
            options={
                'db_table': 'solution',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='authority',
            field=models.IntegerField(default=0, verbose_name='user authority'),
        ),
        migrations.RemoveField(
            model_name='solutioninfo',
            name='like',
        ),
        migrations.AddField(
            model_name='probleminfo',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='aid_platform.CourseInfo', verbose_name='belong course'),
        ),
        migrations.AddField(
            model_name='solutioninfo',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='aid_platform.ProblemInfo', verbose_name='solution belong'),
        ),
        migrations.CreateModel(
            name='LikeUser2Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_platform.SolutionInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_platform.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CommentUser2Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_platform.SolutionInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_platform.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionUser2Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_platform.SolutionInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_platform.UserInfo')),
            ],
        ),
    ]
