# Generated by Django 2.2 on 2022-11-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0002_auto_20221126_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='like',
            field=models.ManyToManyField(related_name='like', through='aid_platform.LikeUser2Solution', to='aid_platform.SolutionInfo'),
        ),


        migrations.AddField(
            model_name='userinfo',
            name='collection',
            field=models.ManyToManyField(related_name='collection', through='aid_platform.CollectionUser2Solution', to='aid_platform.SolutionInfo'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='comment',
            field=models.ManyToManyField(related_name='comment', through='aid_platform.CommentUser2Solution', to='aid_platform.SolutionInfo'),
        ),
    ]
