# Generated by Django 2.2 on 2022-11-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0003_auto_20221129_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=8, verbose_name='label name')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aid_platform.CourseInfo', verbose_name='label belong')),
            ],
        ),
        migrations.CreateModel(
            name='MarkProblem2Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_platform.LabelInfo')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_platform.ProblemInfo')),
            ],
        ),
        migrations.AddField(
            model_name='probleminfo',
            name='mark',
            field=models.ManyToManyField(related_name='mark', through='aid_platform.MarkProblem2Label', to='aid_platform.LabelInfo'),
        ),
    ]
