# Generated by Django 2.2 on 2022-11-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0005_auto_20221129_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyUser2Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_platform.CourseInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_platform.UserInfo')),
            ],
            options={
                'db_table': 'study',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='study',
            field=models.ManyToManyField(related_name='study', through='aid_platform.StudyUser2Course', to='aid_platform.CourseInfo'),
        ),
    ]
