# Generated by Django 2.2 on 2022-11-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0006_auto_20221129_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentuser2solution',
            name='comment_content',
            field=models.TextField(null=True, verbose_name='comment content'),
        ),
        migrations.AddField(
            model_name='solutioninfo',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='solution is checked or not'),
        ),
        migrations.AddField(
            model_name='solutioninfo',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aid_platform.UserInfo', verbose_name='publisher id'),
        ),
    ]
