# Generated by Django 2.2 on 2022-11-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0007_auto_20221129_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutioninfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
