# Generated by Django 2.2 on 2022-11-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0008_auto_20221129_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyuser2course',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='studyuser2course',
            old_name='user',
            new_name='user_id',
        ),
    ]
