# Generated by Django 2.2 on 2022-12-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0009_auto_20221130_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyuser2course',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studyuser2course',
            old_name='user_id',
            new_name='user',
        ),
    ]
