# Generated by Django 2.2 on 2022-12-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0010_auto_20221201_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminfo',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='aid_platform.CourseInfo', verbose_name='belong course'),
        ),
    ]
