# Generated by Django 2.2 on 2022-12-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0012_auto_20221202_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleminfo',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='is solved or not'),
        ),
    ]
