# Generated by Django 2.2 on 2022-12-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0013_probleminfo_is_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinfo',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='label', to='aid_platform.CourseInfo', verbose_name='label belong'),
        ),
        migrations.AlterField(
            model_name='solutioninfo',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='aid_platform.ProblemInfo', verbose_name='solution belong'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.FloatField(default=1670054973009, verbose_name='last login time'),
        ),

    ]
