# Generated by Django 2.2 on 2022-12-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0014_auto_20221202_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='instructor',
            new_name='instructor_id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_login',
            field=models.FloatField(default=1670055334073, verbose_name='last login time'),
        ),
    ]
