# Generated by Django 2.2 on 2022-12-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0015_auto_20221203_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='aid_platform.UserInfo', verbose_name='course instructor'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_login',
            field=models.FloatField(default=1670056075287, verbose_name='last login time'),
        ),
    ]
