# Generated by Django 2.2 on 2022-12-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0016_auto_20221203_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_login',
            field=models.FloatField(default=1670056200938, verbose_name='last login time'),
        ),
    ]
