# Generated by Django 2.2 on 2022-12-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0017_auto_20221203_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_login',
            field=models.BigIntegerField(default=1670056405518, verbose_name='last login time'),
        ),
    ]
