# Generated by Django 2.2 on 2022-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0019_auto_20221203_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentuser2solution',
            old_name='comment_content',
            new_name='commentContent',
        ),
        migrations.RenameField(
            model_name='courseinfo',
            old_name='course_name',
            new_name='courseName',
        ),
        migrations.RenameField(
            model_name='labelinfo',
            old_name='label_name',
            new_name='labelName',
        ),
        migrations.RenameField(
            model_name='probleminfo',
            old_name='is_solved',
            new_name='isSolved',
        ),
        migrations.RenameField(
            model_name='probleminfo',
            old_name='problem_content',
            new_name='problemContent',
        ),
        migrations.RenameField(
            model_name='probleminfo',
            old_name='problem_name',
            new_name='problemName',
        ),
        migrations.RenameField(
            model_name='probleminfo',
            old_name='solution_count',
            new_name='solutionCount',
        ),
        migrations.RenameField(
            model_name='solutioninfo',
            old_name='is_checked',
            new_name='isChecked',
        ),
        migrations.RenameField(
            model_name='solutioninfo',
            old_name='solution_content',
            new_name='solutionContent',
        ),
        migrations.RenameField(
            model_name='solutioninfo',
            old_name='solution_name',
            new_name='solutionName',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='loggedAt',
            field=models.BigIntegerField(default=1670062909058, verbose_name='last login time'),
        ),
    ]
