# Generated by Django 2.2 on 2022-12-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0020_auto_20221203_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionuser2solution',
            name='savedAt',
            field=models.BigIntegerField(default=1670071229114),
        ),
        migrations.AddField(
            model_name='commentuser2solution',
            name='changedAt',
            field=models.BigIntegerField(default=1670071229113),
        ),
        migrations.AddField(
            model_name='commentuser2solution',
            name='commentAt',
            field=models.BigIntegerField(default=1670071229113),
        ),
        migrations.AddField(
            model_name='likeuser2solution',
            name='likedAt',
            field=models.BigIntegerField(default=1670071229114),
        ),
        migrations.AddField(
            model_name='markproblem2label',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aid_platform.CourseInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='probleminfo',
            name='changedAt',
            field=models.BigIntegerField(default=1670071229112),
        ),
        migrations.AddField(
            model_name='probleminfo',
            name='createdAt',
            field=models.BigIntegerField(default=1670071229112),
        ),
        migrations.AddField(
            model_name='solutioninfo',
            name='changedAt',
            field=models.BigIntegerField(default=1670071229112),
        ),
        migrations.AddField(
            model_name='solutioninfo',
            name='createdAt',
            field=models.BigIntegerField(default=1670071229112),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='loggedAt',
            field=models.BigIntegerField(default=1670071229111, verbose_name='last login time'),
        ),
    ]
