# Generated by Django 2.2 on 2022-12-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0021_auto_20221203_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionuser2solution',
            name='savedAt',
            field=models.BigIntegerField(default=1670129481726),
        ),
        migrations.AlterField(
            model_name='commentuser2solution',
            name='changedAt',
            field=models.BigIntegerField(default=1670129481726),
        ),
        migrations.AlterField(
            model_name='commentuser2solution',
            name='commentAt',
            field=models.BigIntegerField(default=1670129481726),
        ),
        migrations.AlterField(
            model_name='likeuser2solution',
            name='likedAt',
            field=models.BigIntegerField(default=1670129481727),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='changedAt',
            field=models.BigIntegerField(default=1670129481724),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='createdAt',
            field=models.BigIntegerField(default=1670129481724),
        ),
        migrations.AlterField(
            model_name='solutioninfo',
            name='changedAt',
            field=models.BigIntegerField(default=1670129481725),
        ),
        migrations.AlterField(
            model_name='solutioninfo',
            name='createdAt',
            field=models.BigIntegerField(default=1670129481725),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='loggedAt',
            field=models.BigIntegerField(default=1670129481723, verbose_name='last login time'),
        ),
    ]
