# Generated by Django 2.2 on 2022-12-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0022_auto_20221204_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionuser2solution',
            name='savedAt',
            field=models.BigIntegerField(default=1670129801941),
        ),
        migrations.AlterField(
            model_name='commentuser2solution',
            name='changedAt',
            field=models.BigIntegerField(default=1670129801941),
        ),
        migrations.AlterField(
            model_name='commentuser2solution',
            name='commentAt',
            field=models.BigIntegerField(default=1670129801941),
        ),
        migrations.AlterField(
            model_name='likeuser2solution',
            name='likedAt',
            field=models.BigIntegerField(default=1670129801942),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='changedAt',
            field=models.BigIntegerField(default=1670129801939),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='createdAt',
            field=models.BigIntegerField(default=1670129801939),
        ),
        migrations.AlterField(
            model_name='solutioninfo',
            name='changedAt',
            field=models.BigIntegerField(default=1670129801940),
        ),
        migrations.AlterField(
            model_name='solutioninfo',
            name='createdAt',
            field=models.BigIntegerField(default=1670129801940),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='loggedAt',
            field=models.BigIntegerField(default=1670129801938, verbose_name='last login time'),
        ),
    ]
