# Generated by Django 2.2 on 2022-12-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_platform', '0023_auto_20221204_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionuser2solution',
            name='savedAt',
            field=models.BigIntegerField(default=1670130069089),
        ),
        migrations.AlterField(
            model_name='commentuser2solution',
            name='changedAt',
            field=models.BigIntegerField(default=1670130069088),
        ),
        migrations.AlterField(
            model_name='commentuser2solution',
            name='commentAt',
            field=models.BigIntegerField(default=1670130069088),
        ),
        migrations.AlterField(
            model_name='likeuser2solution',
            name='likedAt',
            field=models.BigIntegerField(default=1670130069089),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='changedAt',
            field=models.BigIntegerField(default=1670130069087),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='createdAt',
            field=models.BigIntegerField(default=1670130069087),
        ),
        migrations.AlterField(
            model_name='solutioninfo',
            name='changedAt',
            field=models.BigIntegerField(default=1670130069088),
        ),
        migrations.AlterField(
            model_name='solutioninfo',
            name='createdAt',
            field=models.BigIntegerField(default=1670130069088),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='loggedAt',
            field=models.BigIntegerField(default=1670130069086, verbose_name='last login time'),
        ),
    ]
